name: Build/Release
on:
  push:
    branches:
      - 335-支持修改资源请求地址
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Release for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          cd apps/electron
          ls ./
          pnpm release:mac
        env:
          USE_HARD_LINKS: false

      - name: Release for Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd apps/electron
          ls ./
          pnpm release:win

      - name: Release for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd apps/electron
          ls ./
          pnpm release:linux

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            apps/electron/dist/mac/*.dmg
            apps/electron/dist/mac/*.dmg.blockmap
            apps/electron/dist/win/*.exe
            apps/electron/dist/win/*.exe.blockmap
            apps/electron/dist/linux-*/*.deb
          draft: true
